Extension { #name : 'FamixF77IntrinsicRoutine' }

{ #category : '*Famix-Esope-Transformator' }
FamixF77IntrinsicRoutine >> migratedModuleName [

	^''
]

{ #category : '*Famix-Esope-Transformator' }
FamixF77IntrinsicRoutine >> needsUseForProcedure: aFASTFortran2kProcedure [

	^false
]

{ #category : '*Famix-Esope-Transformator' }
FamixF77IntrinsicRoutine >> needsUseForProgramMain: aFASTFortran2kProgramMain [

	^false
]
