"
I am the super class of all Fortran Literals


"
Class {
	#name : 'FASTFortran2kAbstractLiteral',
	#superclass : 'FASTFortran2kAbstractExpression',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kAbstractLiteral class >> annotation [

	<FMClass: #AbstractLiteral super: #FASTFortran2kAbstractExpression>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
