"
a scalar Fortran Variable, used in declarations


"
Class {
	#name : 'FASTFortran2kScalarVariable',
	#superclass : 'FASTFortran2kVariable',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kScalarVariable class >> annotation [

	<FMClass: #ScalarVariable super: #FASTFortran2kVariable>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
