"
I represent Fortran Rewind statement


"
Class {
	#name : 'FASTFortran2kRewindStatement',
	#superclass : 'FASTFortran2kAbstractIOStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kRewindStatement class >> annotation [

	<FMClass: #RewindStatement super: #FASTFortran2kAbstractIOStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
