"
I represent Fortran accept statement


"
Class {
	#name : 'FASTFortran2kAcceptStatement',
	#superclass : 'FASTFortran2kAbstractStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kAcceptStatement class >> annotation [

	<FMClass: #AcceptStatement super: #FASTFortran2kAbstractStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
