"
I represent Fortran Do While statement


"
Class {
	#name : 'FASTFortran2kDoWhileStatement',
	#superclass : 'FASTFortran2kConditionalStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kDoWhileStatement class >> annotation [

	<FMClass: #DoWhileStatement super: #FASTFortran2kConditionalStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
