"
I represent a internal procedure


"
Class {
	#name : 'FASTFortran2kInternalSubroutine',
	#superclass : 'FASTFortran2kInternalProcedure',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kInternalSubroutine class >> annotation [

	<FMClass: #InternalSubroutine super: #FASTFortran2kInternalProcedure>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
