"
I represent Fortran Complex type COMPLEX, ie. a pair of REAL*4 values


"
Class {
	#name : 'FASTFortran2kComplexType',
	#superclass : 'FASTFortran2kType',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kComplexType class >> annotation [

	<FMClass: #ComplexType super: #FASTFortran2kType>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
