"
I represent a derived type declaration


"
Class {
	#name : 'FASTFortran2kDerivedTypeDeclaration',
	#superclass : 'FASTFortran2kVariableDeclarationStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kDerivedTypeDeclaration class >> annotation [

	<FMClass: #DerivedTypeDeclaration super: #FASTFortran2kVariableDeclarationStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
