"
I represent an attribute (pass/nopass or deferred/non_overidable or private/public) of a type-bound-procedure


"
Trait {
	#name : 'FASTFortran2kTHasBindingAttribute',
	#category : 'FAST-Fortran2k-Entities-Traits',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Traits'
}

{ #category : 'meta' }
FASTFortran2kTHasBindingAttribute classSide >> annotation [

	<FMClass: #THasBindingAttribute super: #Object>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
