"
I represent an interface module function declaration


"
Class {
	#name : 'FASTFortran2kInterfaceModuleFunction',
	#superclass : 'FASTFortran2kInterfaceProcedure',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kInterfaceModuleFunction class >> annotation [

	<FMClass: #InterfaceModuleFunction super: #FASTFortran2kInterfaceProcedure>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
