"
I represent a function call statement


"
Class {
	#name : 'FASTFortran2kFunctionCallStatement',
	#superclass : 'FASTFortran2kEntity',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kFunctionCallStatement class >> annotation [

	<FMClass: #FunctionCallStatement super: #FASTFortran2kEntity>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
