"
I represent Fortran Arithmetic Complex Literal (Constant)


"
Class {
	#name : 'FASTFortran2kComplexLiteral',
	#superclass : 'FASTFortran2kNumericalConstant',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTFortran2kNumericalConstant>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
