"
I represent Fortran Include statement


"
Class {
	#name : 'FASTFortran2kIncludeStatement',
	#superclass : 'FASTFortran2kAbstractStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kIncludeStatement class >> annotation [

	<FMClass: #IncludeStatement super: #FASTFortran2kAbstractStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
