"
I represent an empty statement, maybe useful to add empty line


"
Class {
	#name : 'FASTFortran2kEmptyStatement',
	#superclass : 'FASTFortran2kAbstractStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kEmptyStatement class >> annotation [

	<FMClass: #EmptyStatement super: #FASTFortran2kAbstractStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
