"
I represent Fortran Map statement


"
Class {
	#name : 'FASTFortran2kMapStatement',
	#superclass : 'FASTFortran2kAbstractStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kMapStatement class >> annotation [

	<FMClass: #MapStatement super: #FASTFortran2kAbstractStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
