Class {
	#name : 'FASTFortran2kIModuleProcedureSummary',
	#superclass : 'FASTFortran2kInterfaceProcedure',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kIModuleProcedureSummary class >> annotation [

	<FMClass: #IModuleProcedureSummary super: #FASTFortran2kInterfaceProcedure>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
