"
`class(type_name) [, pointer/allocatable/target] [, other_attributes ] :: declarators`


"
Class {
	#name : 'FASTFortran2kClassDeclarationStatement',
	#superclass : 'FASTFortran2kVariableDeclarationStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kClassDeclarationStatement class >> annotation [

	<FMClass: #ClassDeclarationStatement super: #FASTFortran2kVariableDeclarationStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
