"
I represent an interface module subroutine declaration


"
Class {
	#name : 'FASTFortran2kInterfaceModuleSubroutine',
	#superclass : 'FASTFortran2kInterfaceProcedure',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kInterfaceModuleSubroutine class >> annotation [

	<FMClass: #InterfaceModuleSubroutine super: #FASTFortran2kInterfaceProcedure>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
