"
I represent Fortran Substring


"
Class {
	#name : 'FASTFortran2kSubstring',
	#superclass : 'FASTFortran2kAbstractExpression',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kSubstring class >> annotation [

	<FMClass: #Substring super: #FASTFortran2kAbstractExpression>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
