"
I represent Fortran Real type, synonym REAL*4


"
Class {
	#name : 'FASTFortran2kRealType',
	#superclass : 'FASTFortran2kType',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kRealType class >> annotation [

	<FMClass: #RealType super: #FASTFortran2kType>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
