"
I represent Fortran Character Literal


"
Class {
	#name : 'FASTFortran2kCharacterType',
	#superclass : 'FASTFortran2kType',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kCharacterType class >> annotation [

	<FMClass: #CharacterType super: #FASTFortran2kType>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
