"
I represent Fortran Integer type


"
Class {
	#name : 'FASTFortran2kIntegerType',
	#superclass : 'FASTFortran2kType',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kIntegerType class >> annotation [

	<FMClass: #IntegerType super: #FASTFortran2kType>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
