"
The BLOCK DATA statement identifies a subprogram that initializes variables and arrays in labeled common blocks.


"
Class {
	#name : 'FASTFortran2kBlockData',
	#superclass : 'FASTFortran2kSubprogram',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kBlockData class >> annotation [

	<FMClass: #BlockData super: #FASTFortran2kSubprogram>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
