"
I represent a fortran subprogram: procedure or block data


"
Class {
	#name : 'FASTFortran2kSubprogram',
	#superclass : 'FASTFortran2kProgramUnit',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kSubprogram class >> annotation [

	<FMClass: #Subprogram super: #FASTFortran2kProgramUnit>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
