"
I represent a finalizer


"
Class {
	#name : 'FASTFortran2kTypePBFinal',
	#superclass : 'FASTFortran2kTypeBoundProcedure',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kTypePBFinal class >> annotation [

	<FMClass: #TypePBFinal super: #FASTFortran2kTypeBoundProcedure>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
