"
I represent Fortran Close statement


"
Class {
	#name : 'FASTFortran2kCloseStatement',
	#superclass : 'FASTFortran2kAbstractIOStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kCloseStatement class >> annotation [

	<FMClass: #CloseStatement super: #FASTFortran2kAbstractIOStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
