"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `derivedTypeDefinition` | `FASTFortran2kDerivedTypeParameter` | `derivedTypeParameters` | `FASTFortran2kDerivedTypeDefinition` | |



"
Class {
	#name : 'FASTFortran2kDerivedTypeParameter',
	#superclass : 'FASTFortran2kDerivedTypeAbstractField',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kDerivedTypeParameter class >> annotation [

	<FMClass: #DerivedTypeParameter super: #FASTFortran2kDerivedTypeAbstractField>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
