"
I represent Fortran Double Precision type, synonym of REAL*8


"
Class {
	#name : 'FASTFortran2kDoublePrecisionType',
	#superclass : 'FASTFortran2kType',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kDoublePrecisionType class >> annotation [

	<FMClass: #DoublePrecisionType super: #FASTFortran2kType>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
