"
I represent Fortran Open statement


"
Class {
	#name : 'FASTFortran2kOpenStatement',
	#superclass : 'FASTFortran2kAbstractIOStatement',
	#category : 'FAST-Fortran2k-Entities-Entities',
	#package : 'FAST-Fortran2k-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTFortran2kOpenStatement class >> annotation [

	<FMClass: #OpenStatement super: #FASTFortran2kAbstractIOStatement>
	<package: #'FAST-Fortran2k-Entities'>
	<generated>
	^ self
]
