name: Test and update release

on:
  push:
    branches:
      - v1
#  schedule:
#    - cron:  '0 0 * * *'
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  run-tests-and-update-release:
    name: Run tests and update release
    uses: moosetechnology/.github/.github/workflows/test-and-release.yml@main
    with:
      pre-upload-script: "MooseVersion current commitHash: '$GITHUB_SHA'. (Smalltalk tools toolNamed: #mooseWelcome) closePharoWelcomeThenOpen"
